baseURL                = "https://huluhuluu.github.io/"
languageCode           = "zh"
title                  = "huluhuluu"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh"
# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[sitemap]
    changefreq = "weekly"
    filename   = "sitemap.xml"
    priority   = 0.5

# Mount MNN-TUTORIAL blog content as separate posts
[module]
    [[module.mounts]]
        source = "content"
        target = "content"
        excludeFiles = ["post/mnn-tutorial/blog/**"]
    [[module.mounts]]
        source = "content/post/mnn-tutorial/blog"
        target = "content/post"